### ISSUE TITLE
PersistedGrant is missing Id

### ISSUE THREAD

**Issue by raoranjeet** [diogodamiani/IdentityServer4.MongoDB#21]
Using IS4 2.3.2 and getting FormatException: Element '_id' does not match any field or property of class IdentityServer4.MongoDB.Entities.PersistedGrant.  I see that PersistedGrant model has Id property commented out, is this the reason for the error?

Full stack trace:

System.FormatException: Element '_id' does not match any field or property of class IdentityServer4.MongoDB.Entities.PersistedGrant.
   at MongoDB.Driver.Linq.MongoQueryProviderImpl`1.Execute(Expression expression)
   at MongoDB.Driver.Linq.MongoQueryProviderImpl`1.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at IdentityServer4.MongoDB.Stores.PersistedGrantStore.GetAsync(String key) in I:\projects\git\IdentityServer4.Contrib.MongoDB\src\IdentityServer4.MongoDB\Stores\PersistedGrantStore.cs:line 45
   at IdentityServer4.Stores.DefaultGrantStore`1.GetItemAsync(String key) in C:\local\identity\server4\IdentityServer4\src\Stores\Default\DefaultGrantStore.cs:line 89
   at IdentityServer4.Services.DefaultConsentService.RequiresConsentAsync(ClaimsPrincipal subject, Client client, IEnumerable`1 scopes) in C:\local\identity\server4\IdentityServer4\src\Services\Default\DefaultConsentService.cs:line 97
   at IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator.ProcessConsentAsync(ValidatedAuthorizeRequest request, ConsentResponse consent) in C:\local\identity\server4\IdentityServer4\src\ResponseHandling\Default\AuthorizeInteractionResponseGenerator.cs:line 240
   at IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator.ProcessInteractionAsync(ValidatedAuthorizeRequest request, ConsentResponse consent) in C:\local\identity\server4\IdentityServer4\src\ResponseHandling\Default\AuthorizeInteractionResponseGenerator.cs:line 89
   at IdentityServer4.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, ConsentResponse consent) in C:\local\identity\server4\IdentityServer4\src\Endpoints\AuthorizeEndpointBase.cs:line 81
   at IdentityServer4.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\Endpoints\AuthorizeEndpoint.cs:line 55
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 54
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 69
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by raoranjeet** [comment]
Uncommenting Id property in PersistedGrant causes duplicate entity errors.  I got this working by decorating PersistedGrant class with [BsonIgnoreExtraElements] attribute.  Is this an acceptable fix ?

**Comment by diogodamiani** [comment]
@raoranjeet, 
I'll try to reproduce the error, and let you know. I think that BsonIgnoreExtraElements att isn't the correct fix.

**Comment by tioma18** [comment]
temporary solution: add in startup.cs
`            ConventionRegistry.Register("Ignore extra properties",
                new ConventionPack {new IgnoreExtraElementsConvention(true)}, type => true);`

**Comment by diogodamiani** [comment]
@raoranjeet and @tioma18,
Fix released at 2.3.3. Let me know if you have any problems.
Thanks.
