### ISSUE TITLE
Some problem on ApiResource seed data

### ISSUE THREAD

**Issue by diogodamiani** [diogodamiani/IdentityServer4.MongoDB#29]
I need to dig deeper on this:
![image](https://user-images.githubusercontent.com/573679/89182486-2f999500-d56c-11ea-88bf-987fe5d1cf97.png)

**Comment by tbureck** [comment]
I think the issue is that the type of `ApiResource.Scopes` has changed. Hence the mappers do not work anymore. In Identity Server v3.1.4 it was:

```
public ICollection<Scope> Scopes { get; set; } = new HashSet<Scope>();
```
While from Identity Server v4.0.0-preview.3 it is:

```
public ICollection<string> Scopes { get; set; } = new HashSet<string>();
```

The change is part of [this little commit](https://github.com/IdentityServer/IdentityServer4/commit/51a011e638375eea4626c3d5ffb04691fa0ba911) which changed 205 files. Yikes.

Full stack trace of the issue:

```
Mapping types:
ApiResource -> ApiResource
IdentityServer4.Models.ApiResource -> IdentityServer4.MongoDB.Entities.ApiResource

Type Map configuration:
ApiResource -> ApiResource
IdentityServer4.Models.ApiResource -> IdentityServer4.MongoDB.Entities.ApiResource

Destination Member:
Scopes

 ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
String -> ApiScope
System.String -> IdentityServer4.MongoDB.Entities.ApiScope
   at lambda_method(Closure , String , ApiScope , ResolutionContext )
   at lambda_method(Closure , Object , ApiResource , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , ApiResource , ResolutionContext )
   at IdentityServer4.MongoDB.Mappers.ApiResourceMappers.ToEntity(ApiResource resource)
   at TBureck.Hub.WebApplication.Startup.EnsureSeedData(IConfigurationDbContext context) in D:\Projects\TBureck\Hub\src\TBureck.Hub.WebApplication\Startup.cs:line 90
   at TBureck.Hub.WebApplication.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in D:\Projects\TBureck\Hub\src\TBureck.Hub.WebApplication\Startup.cs:line 59
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

**Comment by tbureck** [comment]
I made code. Have a look at PR #30.
