### ISSUE TITLE
IdentityServer4.Models.Resource in the expression tree {document}.ToModel().Name cannot be translat

### ISSUE THREAD

**Issue by fengzhanyuan2016** [diogodamiani/IdentityServer4.MongoDB#34]
![image](https://user-images.githubusercontent.com/18228933/92203827-b798f480-eeb4-11ea-8374-8a1b58f2c5c5.png)

 var models = _context.ApiScopes.Where(x => names.Contains(x.Name)).Select(x => x.ToModel());

**Comment by fengzhanyuan2016** [comment]
should ToLlist  before  Select

**Comment by fengzhanyuan2016** [comment]
ToLlist  before  Select

**Comment by diogodamiani** [comment]
Hi,
Does it seem to be related to this? https://jira.mongodb.org/browse/CSHARP-2008

**Comment by fengzhanyuan2016** [comment]
> Hi,
> Does it seem to be related to this? https://jira.mongodb.org/browse/CSHARP-2008

![image](https://user-images.githubusercontent.com/18228933/92296477-b96fc000-ef67-11ea-8a0b-49d91e3dd500.png)
Yes,  But when  I change the code like this,  it worked

**Comment by paulyipkh** [comment]
System.NotSupportedException: ToModel of type IdentityServer4.MongoDB.Mappers.ApiScopeMappers is not supported in the expression tree {document}.ToModel().
   at MongoDB.Driver.Linq.Translators.AggregateLanguageTranslator.TranslateMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Translators.AggregateLanguageTranslator.TranslateValue(Expression node)
   at MongoDB.Driver.Linq.Translators.AggregateLanguageTranslator.TranslateDocumentWrappedField(FieldAsDocumentExpression expression)
   at MongoDB.Driver.Linq.Translators.AggregateLanguageTranslator.TranslateValue(Expression node)
   at MongoDB.Driver.Linq.Translators.AggregateLanguageTranslator.Translate(Expression node, ExpressionTranslationOptions translationOptions)
   at MongoDB.Driver.Linq.Translators.QueryableTranslator.TranslateProjectValue(Expression selector)
   at MongoDB.Driver.Linq.Translators.QueryableTranslator.TranslateSelect(SelectExpression node)
   at MongoDB.Driver.Linq.Translators.QueryableTranslator.Translate(Expression node)
   at MongoDB.Driver.Linq.Translators.QueryableTranslator.TranslatePipeline(PipelineExpression node)
   at MongoDB.Driver.Linq.Translators.QueryableTranslator.Translate(Expression node)
   at MongoDB.Driver.Linq.Translators.QueryableTranslator.Translate(Expression node, IBsonSerializerRegistry serializerRegistry, ExpressionTranslationOptions translationOptions)
   at MongoDB.Driver.Linq.MongoQueryProviderImpl`1.Translate(Expression expression)
   at MongoDB.Driver.Linq.MongoQueryProviderImpl`1.Execute(Expression expression)
   at MongoDB.Driver.Linq.MongoQueryableImpl`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at IdentityServer4.Stores.IResourceStoreExtensions.GetDuplicates(IEnumerable`1 names)
   at IdentityServer4.Stores.IResourceStoreExtensions.Validate(IEnumerable`1 identity, IEnumerable`1 apiResources, IEnumerable`1 apiScopes)
   at IdentityServer4.Stores.IResourceStoreExtensions.FindResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames)
   at IdentityServer4.Stores.IResourceStoreExtensions.FindEnabledResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames)
   at IdentityServer4.Validation.DefaultResourceValidator.ValidateRequestedResourcesAsync(ResourceValidationRequest request)
   at IdentityServer4.Validation.AuthorizeRequestValidator.ValidateScopeAsync(ValidatedAuthorizeRequest request)
   at IdentityServer4.Validation.AuthorizeRequestValidator.ValidateAsync(NameValueCollection parameters, ClaimsPrincipal subject)
   at IdentityServer4.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, ConsentResponse consent)
   at IdentityServer4.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I think I encountered a related problem. It didn't go away even when I had added ToList() query before calling ToModel()

**Comment by tbureck** [comment]
This happens because we're still in the IQueryable (read: MongoQueryProviderImpl) context when doing the `Select` mapping. It will try to convert that to a query, which fails, because, well, `ToModel` is not part of the actual entity.

Hence, the actual query (`Where` call) needs to be collected first, only then the mapping can take place. I've opened a PR that should fix that issue.

_Note:_ according to the other query methods, I'm using `ToArray` instead of `ToList`

**Comment by diogodamiani** [comment]
Fixed in 4.0.0-rc.2
